name: "CI"
on: [push]
permissions:
  contents: read
jobs:
  test:
    name: Test on go ${{ matrix.go_version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ["1.20"]
        os: [ubuntu-latest]
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}
          cache: false
        id: go
      - name: Setup gotip
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: gotip test -v -cover ./...
